In [1]:
import sys
sys.path.insert(0,'../python/')
from OpticalPhoton import *
import matplotlib.pyplot as plt
import matplotlib as mpl

In [2]:
from Generator import *

In [3]:
gen = Generator()

Generator::Reading configuration from file: config.json
OpticalPhoton::Reading configuration from file: config.json


In [4]:
gen.generate_batch(10)

number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine
number
true_position
pmt
fine


0

In [6]:
import h5py
import json

# Open the HDF5 file in read mode
with h5py.File('dummy.hd5f', 'r') as hf:
    
    # Access the 'config' group
    config = json.loads(hf.attrs['config'])
    print(config)
    print(config['geometry']['radius'])
    

    # Print the structure of the 'events' dataset
    events = hf['events']
    print(events)

    # Iterate over the elements in the dataset
    for event in events:
        event = events[event]
        # Print the structure of each element
        print(event['number'][()])
        print(np.array(event['true_position']))
        print(np.array(event['pmt']))
        print(np.array(event['fine']))
        

        # Access the data within each element
        #data = str(event[()]
        #print(data)



{'filename': 'dummy.hd5f', 'nevents': 100, 'nphoton_per_event': 10000, 'photon_zgen': 0.1, 'geometry': {'type': 'cylinder', 'radius': 2.5, 'ztop': 1.0, 'zliq': 0.0, 'zbot': -10.0}, 'npmt_xy': 2, 'pmt': {'type': 'square', 'size': 2.54, 'ndivs': 5}}
2.5
<HDF5 group "/events" (10 members)>
0
[-2.12946066 -0.15485173  0.1       ]
[[1114  830]
 [  93   82]]
[[  0   0  16  74 194 153  60  15   0   0]
 [  0  17  50 135 182 142  79  31   9   0]
 [  2  21  46  69 104  84  46  25  25   4]
 [  6   9  41  33  37  34  29  22   6   5]
 [  9  12  12  26  19  21  14  14   6   6]
 [  8   4   8  11  13   9  10  10   7   4]
 [  1   4   6  13   6   7   4   6   2   3]
 [  0   1   1   6   2   4   2   4   2   1]
 [  0   0   2   3   1   0   2   2   0   0]
 [  0   0   1   0   2   1   1   1   0   0]]
1
[-1.11251866 -1.06342738  0.1       ]
[[2025  361]
 [ 339  119]]
[[  0   0  15  36  30  24  10   7   0   0]
 [  0  43 143 145  73  43  14   7   3   0]
 [ 19 117 199 201  85  46  30   8   8   1]
 [ 54 105 199 155 